### ISSUE TITLE
AWS Testing documentation structure

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/aws-testing#1]
Define the main structure of the documentation, including ToC and highlights of each section

**Comment by szikszail** [comment]
Topics to be covered:

1. General AWS topics
   1. Cloud, AWS
   1. Tools
      1. AWS CLI - https://aws.amazon.com/cli/
      1. AWS SDK - https://www.npmjs.com/package/aws-sdk
      1. AWS CDK - https://aws.amazon.com/cdk/
      1. AWS SAM - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-command-reference.html
      1. AWS Console - https://aws.amazon.com/console/
1. Cover in general testing types applied for AWS:
   1. Manual testing
      - https://www.techmagic.co/blog/aws-testing-tools/
      - https://aws-quickstart.github.io/manual-testing.html
   1. Unit testing
      - https://aws.amazon.com/blogs/devops/performing-unit-testing-in-an-aws-codestar-project/
      - https://github.com/aws-samples/aws-unit-testing
      - https://towardsdatascience.com/how-i-write-meaningful-tests-for-aws-lambda-functions-f009f0a9c587
      - https://lumigo.io/debugging-aws-lambda-serverless-applications/aws-lambda-unit-testing/
   1. CDK / Infrastructure testing
      - https://aws.amazon.com/blogs/developer/testing-infrastructure-with-the-aws-cloud-development-kit-cdk/
      - https://aws-cdk-assert.ideapool.community/
      - https://aws.amazon.com/blogs/infrastructure-and-automation/best-practices-automating-deployments-with-aws-cloudformation/
   1. Integration testing
   1. System testing
   1. Performance testing
      - https://aws.amazon.com/solutions/implementations/distributed-load-testing-on-aws/
   1. Security testing
      - https://www.intruder.io/automated-penetration-testing
      - https://aws.amazon.com/security/penetration-testing/
   1. Chaos testing
      - https://aws.amazon.com/fis/
      - https://aws.amazon.com/blogs/architecture/chaos-testing-with-aws-fault-injection-simulator-and-aws-codepipeline/
      - https://medium.com/the-cloud-architect/what-is-aws-fault-injection-simulator-and-why-you-should-care-3fbe457ca227
      - https://www.gremlin.com/aws/
1. Cover each service from the aspects above:
   1. Lambda
   1. Step Functions / State Machines
   1. S3
   1. IAM
   1. DynamoDB / RDS
   1. SQS
   1. SNS
   1. Events
   1. EC2
   1. ECS
   1. ELB
   1. VPC
   1. API Gateway
   1. Glue
   1. Athena
   1. ...
1. Mocking
1. Tools, Libraries

**Comment by kornel-filep** [comment]
I think adding these to 3. would be reasonable:

- ECS - EC2 is there, but most services are clusters, not single instances
- ELB - load balancing is a big thing in AWS, worth to test it. ELB combined with Multi-region/Out-of-region testing is advised as well.

**Comment by szikszail** [comment]
Page structure has been created: https://aws-testing.ideapool.community/
